export const ALL_STUDENTS = [
  { id: 1, name: 'Juan Dela Cruz', studentId: 'STU001', year: '3rd Year', program: 'BS Computer Science' },
  { id: 2, name: 'Maria Santos', studentId: 'STU002', year: '2nd Year', program: 'BS Computer Science' },
  { id: 3, name: 'Carlos Garcia', studentId: 'STU003', year: '3rd Year', program: 'BS Computer Science' },
  { id: 4, name: 'Anna Lopez', studentId: 'STU004', year: '1st Year', program: 'BS Computer Science' },
  { id: 5, name: 'Miguel Reyes', studentId: 'STU005', year: '2nd Year', program: 'BS Computer Science' },
  { id: 6, name: 'Sofia Mendoza', studentId: 'STU006', year: '1st Year', program: 'BS Computer Science' },
  { id: 7, name: 'Diego Tan', studentId: 'STU007', year: '4th Year', program: 'BS Computer Science' },
  { id: 8, name: 'Isabella Chua', studentId: 'STU008', year: '2nd Year', program: 'BS Computer Science' },
  { id: 9, name: 'Rafael Villanueva', studentId: 'STU009', year: '3rd Year', program: 'BS Computer Science' },
  { id: 10, name: 'Gabriella Ramos', studentId: 'STU010', year: '1st Year', program: 'BS Computer Science' },
  { id: 11, name: 'Luis Mercado', studentId: 'STU011', year: '4th Year', program: 'BS Computer Science' },
  { id: 12, name: 'Angela Cruz', studentId: 'STU012', year: '2nd Year', program: 'BS Computer Science' },
  { id: 13, name: 'Mateo Del Rosario', studentId: 'STU013', year: '3rd Year', program: 'BS Computer Science' },
  { id: 14, name: 'Julia Ferrer', studentId: 'STU014', year: '1st Year', program: 'BS Computer Science' },
  { id: 15, name: 'Kyle Santiago', studentId: 'STU015', year: '4th Year', program: 'BS Computer Science' },
];
